services:
  - type: web
    name: chollo-ofertas
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: chollo-ofertas-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: chollo-ofertas-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: chollo-ofertas-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: chollo-ofertas-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: chollo-ofertas-db
          property: password
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error

databases:
  - name: chollo-ofertas-db
    databaseName: chollo_ofertas
    user: chollo_user
    plan: free 