[build]
builder = "dockerfile"

[deploy]
startCommand = "chmod +x start-zeabur.sh && ./start-zeabur.sh"
healthCheckPath = "/"

[env]
APP_NAME = "Chollo Ofertas"
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://chollo-ofertas.zeabur.app"
LOG_CHANNEL = "stack"
LOG_LEVEL = "error"
DB_CONNECTION = "mysql"
CACHE_DRIVER = "file"
FILESYSTEM_DISK = "local"
QUEUE_CONNECTION = "sync"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "120" 