[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan serve --host 0.0.0.0 --port $PORT"
healthCheckPath = "/"

[env]
APP_ENV = "production"
APP_DEBUG = "false"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "120"
LOG_CHANNEL = "stack"
LOG_LEVEL = "error" 