[build]
builder = "nixpacks"

[deploy]
startCommand = "chmod +x start-zeabur.sh && ./start-zeabur.sh"
healthCheckPath = "/"

[env]
APP_ENV = "production"
APP_DEBUG = "false"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "120"
LOG_CHANNEL = "stack"
LOG_LEVEL = "error"
DB_CONNECTION = "mysql" 